#!bin/python3

print("First Repository. Committed from linux terminal")
#Hopefully this works and posts to Github.

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# On branch master
#
# Initial commit
#
# Changes to be committed:
#	new file:   times_tables.py
#
